// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/banners/counter/{bannerID}": {
            "get": {
                "description": "Banner counter inc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banners"
                ],
                "summary": "Счетчик показов баннера по bannerID",
                "operationId": "Banners_counter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "banner id",
                        "name": "bannerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/banners/stats/{bannerID}": {
            "post": {
                "description": "Banners Stat",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banners"
                ],
                "summary": "Статистика показов по bannerID за указанный промежуток времени",
                "operationId": "Banners_stat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "banner id",
                        "name": "bannerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "stat",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Filter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Stats"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Filter": {
            "type": "object",
            "properties": {
                "ts_from": {
                    "type": "string",
                    "example": "2025-04-07T00:00:00Z"
                },
                "ts_to": {
                    "type": "string",
                    "example": "2025-04-07T23:59:00Z"
                }
            }
        },
        "types.Stat": {
            "type": "object",
            "properties": {
                "ts": {
                    "type": "string"
                },
                "v": {
                    "type": "integer"
                }
            }
        },
        "types.Stats": {
            "type": "object",
            "properties": {
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Stat"
                    }
                }
            }
        },
        "v1.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal error"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ekom-test app",
	Description:      "Сервис, который будет считать клики и собирать их в поминутную статистику",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
